name: Build and deploy Node.js app to Azure Web App - imaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Verify the build output (Check for .next folder)
        run: |
          echo "Checking for .next directory"
          dir .  # List all files in the current directory (Windows way)
          dir .next  # Check the .next folder contents (Windows way)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .next/
            node_modules/
            package.json
            package-lock.json
            public/  # Ensure public folder is also included if needed

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List contents of deployment package
        run: |
          echo "Listing contents of the deployment package"
          dir .  # List files in the current directory
          dir node_modules  # List node_modules folder if it's included
          dir .next  # Specifically list contents of the .next folder

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'imaging'
          slot-name: 'Production'
          package: .  # Ensure the full directory with .next is being deployed
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_22B9D88ED3A4477482077FCBF23E8B89 }}