name: Build and deploy Node.js app to Azure Web App - imaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Or windows-latest, depending on your environment

    steps:
      - uses: actions/checkout@v4  # Checkout your code

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies using npm ci
        run: |
          npm ci --unsafe-perm=true --legacy-peer-deps  # Install dependencies

      - name: Build the app (next build)
        run: |
          npm run build  # This generates the .next folder

        # Zip the build directory
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: release.zip
          path: ./build/*
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest  # Deploy using Ubuntu

    needs: build  # Deploy after the build job is completed

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy .zip package to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'imaging'  # Your Azure Web App name
          slot-name: 'Production'  # Your Azure slot name
          package: release.zip  # Path to the uploaded .zip package
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_22B9D88ED3A4477482077FCBF23E8B89 }}  # Your Azure Publish Profile secret
