name: Build and deploy Node.js app to Azure Web App - imaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Create .zip archive for deployment
        run: |
          # Create a deployable directory
          mkdir -p deploy

          # Copy necessary files to the deploy directory
          cp -r .next deploy/.next
          cp -r node_modules deploy/node_modules
          cp -r public deploy/public  # if you have a public folder
          cp server.js deploy/server.js
          cp package.json deploy/package.json
          cp .env.production deploy/.env.production
          cp web.config deploy/web.config
          
          # Zip the deploy directory
          cd deploy
          zip -r ../deployment-package.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'imaging'
          slot-name: 'Production'
          package: deployment-package.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_22B9D88ED3A4477482077FCBF23E8B89 }}
